<?php $zohoAgenciesArray = array (
  0 => 
  array (
    'Modo_de_cobrocvxc' => NULL,
    'Email' => 'jmc.lemonpie@gmail.com',
    'secret' => 'simpass',
    'enabled' => true,
    'Name' => 'Empresa Falsa SA',
    'Record_Image' => NULL,
    'adults_guide_2' => '110',
    'adults_guide_3' => '100',
    'adults_guide_4' => '90',
    'adults_guide_5' => '80',
    'children' => '80',
    'comision' => '5',
    'Email_Opt_Out' => false,
    'guide' => false,
    'payment_method' => NULL,
    'adultos_5' => '90',
    'adultos_4' => '100',
    'children_guide' => '70',
    'Tag' => 
    array (
    ),
    'adults_2' => '120',
    'Secondary_Email' => NULL,
    'adults_3' => '110',
    'username' => 'empfalsa',
    'ID' => '3746000000000581051',
  ),
  1 => 
  array (
    'Modo_de_cobrocvxc' => NULL,
    'Email' => 'jmc.lemonpie@gmail.com',
    'secret' => 'sinpass2005',
    'enabled' => true,
    'Name' => 'Turtest',
    'Record_Image' => NULL,
    'adults_guide_2' => '100',
    'adults_guide_3' => '95',
    'adults_guide_4' => '85',
    'adults_guide_5' => '80',
    'children' => '77',
    'comision' => '12',
    'Email_Opt_Out' => false,
    'guide' => true,
    'payment_method' => NULL,
    'adultos_5' => '89',
    'adultos_4' => '98',
    'children_guide' => '40',
    'Tag' => 
    array (
    ),
    'adults_2' => '115',
    'Secondary_Email' => NULL,
    'adults_3' => '105',
    'username' => 'turtest',
    'ID' => '3746000000000580019',
  ),
);