<?php $arr = array (
  'Canales_de_Venta' => 
  array (
  ),
  'discount' => NULL,
  'validIn' => NULL,
  'notCompatible' => NULL,
  'salesChannel' => NULL,
  'type' => NULL,
  'optionDefault' => false,
  'Gastos_en_la_Isla' => NULL,
  'activityId' => NULL,
  'Nota_D_a_Completo' => NULL,
  'price' => '9',
  'allowChildren' => false,
  'optionPrice' => NULL,
  'sku' => 'software-development',
  'slug' => NULL,
  'order' => NULL,
  'Product_Name' => 'Desarrollo de Software',
  'Tipo_de_Salida' => NULL,
  'slots' => NULL,
  'month' => 
  array (
  ),
  'Special_Activity_Name' => NULL,
  'optionName_en' => NULL,
  'optionId' => NULL,
  'isBase' => false,
  'optionName_es' => NULL,
  'name_es' => 'Desarrollo de Software',
  'Tipo_de_Precio_Despegar' => NULL,
  'mood' => NULL,
  'T_tulo_texto' => NULL,
  'Navegaci_n' => NULL,
  'show' => false,
  'priceVip' => NULL,
  'dow' => 
  array (
  ),
  'Record_Image' => NULL,
  'oil' => NULL,
  'Nota_Medio_D_a' => NULL,
  'Special_Activity_Name_es' => NULL,
  'P_rrafo_1' => NULL,
  'P_rrafo_2' => NULL,
  'description_en' => 'Software Development &  Maintenance',
  'P_rrafo_3' => NULL,
  'Pasajeros_Lancha_Compartida' => NULL,
  'hasActivity' => false,
  'schedule' => NULL,
  'optionLabel_en' => NULL,
  'optionEnabled' => false,
  'optionLabel_es' => NULL,
  'Pago_Web_Compartida' => NULL,
  'P_rrafo_4' => NULL,
  'P_rrafo_5' => NULL,
  'description_es' => 'Desarrollo de Software & Mantenimiento',
  'Tag' => 
  array (
  ),
  'category' => NULL,
  'categoryId' => NULL,
  'name_en' => 'Software Development',
  'Precio_Lancha_Compartida' => NULL,
);